# Generated by Django 3.2.2 on 2021-05-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database_uploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_database', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='database_Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_data', models.TextField()),
            ],
        ),
    ]
